### ISSUE TITLE
Flower and probably celery not working

### ISSUE THREAD

**Issue by tofuwabohu** [bookwyrm-social/bookwyrm#1308]
**Describe the bug**
I can't reach flower on wyrms.de:8888. The flower and celery services are constantly restarting.
(`dc` = `docker-compose`)
```
# dc ps                   
          Name                         Command                 State                       Ports                  
------------------------------------------------------------------------------------------------------------------
bookwyrm_celery_worker_1    celery -A celerywyrm worke ...   Restarting                                           
bookwyrm_certbot_1          certbot renew --webroot -- ...   Exit 0                                               
bookwyrm_db_1               /bookwyrm-entrypoint.sh cr ...   Up           0.0.0.0:5432->5432/tcp                  
bookwyrm_flower_1           flower -A celerywyrm             Restarting                                           
bookwyrm_nginx_1            /docker-entrypoint.sh ngin ...   Up           0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
bookwyrm_redis_activity_1   docker-entrypoint.sh redis ...   Up           6379/tcp                                
bookwyrm_redis_broker_1     docker-entrypoint.sh redis ...   Up           0.0.0.0:6379->6379/tcp                  
bookwyrm_web_1              gunicorn bookwyrm.wsgi:app ...   Up           0.0.0.0:8000->8000/tcp    
```
flower logs:
```
# dc logs --tail 50 flower                
Attaching to bookwyrm_flower_1
flower_1          | Traceback (most recent call last):
flower_1          |   File "/usr/local/bin/flower", line 8, in <module>
flower_1          |     sys.exit(main())
flower_1          |   File "/usr/local/lib/python3.9/site-packages/flower/__main__.py", line 14, in main
flower_1          |     print(bugreport(app=flower.app), file=sys.stderr)
flower_1          |   File "/usr/local/lib/python3.9/site-packages/flower/utils/__init__.py", line 26, in bugreport
flower_1          |     app.bugreport()
flower_1          |   File "/usr/local/lib/python3.9/site-packages/celery/app/base.py", line 939, in bugreport
flower_1          |     return bugreport(self)
flower_1          |   File "/usr/local/lib/python3.9/site-packages/celery/app/utils.py", line 363, in bugreport
flower_1          |     human_settings=app.conf.humanize(),
flower_1          |   File "/usr/local/lib/python3.9/site-packages/celery/app/utils.py", line 199, in humanize
flower_1          |     return '\n'.join(
flower_1          |   File "/usr/local/lib/python3.9/site-packages/celery/app/utils.py", line 200, in <genexpr>
flower_1          |     '{0}: {1}'.format(key, pretty(value, width=50))
flower_1          |   File "/usr/local/lib/python3.9/site-packages/celery/utils/text.py", line 130, in pretty
flower_1          |     return pformat(value, width=width, **kw)
flower_1          |   File "/usr/local/lib/python3.9/pprint.py", line 58, in pformat
flower_1          |     return PrettyPrinter(indent=indent, width=width, depth=depth,
flower_1          |   File "/usr/local/lib/python3.9/pprint.py", line 153, in pformat
flower_1          |     self._format(object, sio, 0, 0, {}, 0)
flower_1          |   File "/usr/local/lib/python3.9/pprint.py", line 170, in _format
flower_1          |     rep = self._repr(object, context, level)
flower_1          |   File "/usr/local/lib/python3.9/pprint.py", line 431, in _repr
flower_1          |     repr, readable, recursive = self.format(object, context.copy(),
flower_1          |   File "/usr/local/lib/python3.9/pprint.py", line 444, in format
flower_1          |     return _safe_repr(object, context, maxlevels, level, self._sort_dicts)
flower_1          |   File "/usr/local/lib/python3.9/pprint.py", line 587, in _safe_repr
flower_1          |     orepr, oreadable, orecur = _safe_repr(o, context, maxlevels, level, sort_dicts)
flower_1          |   File "/usr/local/lib/python3.9/pprint.py", line 587, in _safe_repr
flower_1          |     orepr, oreadable, orecur = _safe_repr(o, context, maxlevels, level, sort_dicts)
flower_1          |   File "/usr/local/lib/python3.9/pprint.py", line 596, in _safe_repr
flower_1          |     rep = repr(object)
flower_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 107, in __repr__
flower_1          |     return repr(self.__cast())
flower_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 152, in __cast
flower_1          |     return self.__text_cast()
flower_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 140, in __text_cast
flower_1          |     return func(*self.__args, **self.__kw)
flower_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/translation/__init__.py", line 94, in gettext
flower_1          |     return _trans.gettext(message)
flower_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/translation/trans_real.py", line 355, in gettext
flower_1          |     _default = _default or translation(settings.LANGUAGE_CODE)
flower_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/translation/trans_real.py", line 268, in translation
flower_1          |     _translations[language] = DjangoTranslation(language)
flower_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/translation/trans_real.py", line 155, in __init__
flower_1          |     self._add_installed_apps_translations()
flower_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/translation/trans_real.py", line 196, in _add_installed_apps_translations
flower_1          |     raise AppRegistryNotReady(
flower_1          | django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.

```

**Additional context**
I updated recently and I'm not sure if it worked before the update. Last state was a few weeks old.
The instance seems to be working so far.

**Comment by mouse-reeve** [comment]
Are there any errors in the celery logs?

**Comment by mouse-reeve** [comment]
I think the problem may be these gettext imports, but I'm not 100%

**Comment by tofuwabohu** [comment]
Oh yes, celery has similar errors!
```
# dc logs --tail 50 flower                
Attaching to bookwyrm_flower_1
flower_1          | Traceback (most recent call last):
flower_1          |   File "/usr/local/bin/flower", line 8, in <module>
flower_1          |     sys.exit(main())
flower_1          |   File "/usr/local/lib/python3.9/site-packages/flower/__main__.py", line 14, in main
flower_1          |     print(bugreport(app=flower.app), file=sys.stderr)
flower_1          |   File "/usr/local/lib/python3.9/site-packages/flower/utils/__init__.py", line 26, in bugreport
flower_1          |     app.bugreport()
flower_1          |   File "/usr/local/lib/python3.9/site-packages/celery/app/base.py", line 939, in bugreport
flower_1          |     return bugreport(self)
flower_1          |   File "/usr/local/lib/python3.9/site-packages/celery/app/utils.py", line 363, in bugreport
flower_1          |     human_settings=app.conf.humanize(),
flower_1          |   File "/usr/local/lib/python3.9/site-packages/celery/app/utils.py", line 199, in humanize
flower_1          |     return '\n'.join(
flower_1          |   File "/usr/local/lib/python3.9/site-packages/celery/app/utils.py", line 200, in <genexpr>
flower_1          |     '{0}: {1}'.format(key, pretty(value, width=50))
flower_1          |   File "/usr/local/lib/python3.9/site-packages/celery/utils/text.py", line 130, in pretty
flower_1          |     return pformat(value, width=width, **kw)
flower_1          |   File "/usr/local/lib/python3.9/pprint.py", line 58, in pformat
flower_1          |     return PrettyPrinter(indent=indent, width=width, depth=depth,
flower_1          |   File "/usr/local/lib/python3.9/pprint.py", line 153, in pformat
flower_1          |     self._format(object, sio, 0, 0, {}, 0)
flower_1          |   File "/usr/local/lib/python3.9/pprint.py", line 170, in _format
flower_1          |     rep = self._repr(object, context, level)
flower_1          |   File "/usr/local/lib/python3.9/pprint.py", line 431, in _repr
flower_1          |     repr, readable, recursive = self.format(object, context.copy(),
flower_1          |   File "/usr/local/lib/python3.9/pprint.py", line 444, in format
flower_1          |     return _safe_repr(object, context, maxlevels, level, self._sort_dicts)
flower_1          |   File "/usr/local/lib/python3.9/pprint.py", line 587, in _safe_repr
flower_1          |     orepr, oreadable, orecur = _safe_repr(o, context, maxlevels, level, sort_dicts)
flower_1          |   File "/usr/local/lib/python3.9/pprint.py", line 587, in _safe_repr
flower_1          |     orepr, oreadable, orecur = _safe_repr(o, context, maxlevels, level, sort_dicts)
flower_1          |   File "/usr/local/lib/python3.9/pprint.py", line 596, in _safe_repr
flower_1          |     rep = repr(object)
flower_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 107, in __repr__
flower_1          |     return repr(self.__cast())
flower_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 152, in __cast
flower_1          |     return self.__text_cast()
flower_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 140, in __text_cast
flower_1          |     return func(*self.__args, **self.__kw)
flower_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/translation/__init__.py", line 94, in gettext
flower_1          |     return _trans.gettext(message)
flower_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/translation/trans_real.py", line 355, in gettext
flower_1          |     _default = _default or translation(settings.LANGUAGE_CODE)
flower_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/translation/trans_real.py", line 268, in translation
flower_1          |     _translations[language] = DjangoTranslation(language)
flower_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/translation/trans_real.py", line 155, in __init__
flower_1          |     self._add_installed_apps_translations()
flower_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/translation/trans_real.py", line 196, in _add_installed_apps_translations
flower_1          |     raise AppRegistryNotReady(
flower_1          | django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.
```
Not sure what to do with this though. Anything else that could help?

**Comment by mouse-reeve** [comment]
I think you may have pasted the wrong log file

**Comment by mouse-reeve** [comment]
It does seem to be hitting an error related translation, which is odd? I'm not having any similar errors locally or on b.s

**Comment by tofuwabohu** [comment]
My bad, edited the celery logs, sorry! 
It's again missing storages, but I already had it installed after the last update.

**Comment by mouse-reeve** [comment]
that's so odd?? were you able to resolve it by installing storages? (that would be `docker-compose exec celery_worker pip install django-storages==1.11.1`, for anyone following along 😉 )

**Comment by tofuwabohu** [comment]
It didn't let me install it with a running container so I forcefully stopped it. Docker suggested to remove redis_activity as it's using /data from the previous container, so I did and then restarted. Now everything is working but the tl was empty - I ran `populate_stream` but the newest posts are from August 7th. Is there a way to get the posts of the last 11 days as well or should I recover (did a full backup before deleting redis_activity)?

**Comment by tofuwabohu** [comment]
Oh, nvm, it seems like entries are coming in slowly, currently at August 8th. Will wait for a while!

**Comment by tofuwabohu** [comment]
Everything's looking good now, thank you! Not sure what the problem was, but the new version is very cool!

**Comment by tofuwabohu** [comment]
Uh, not sure if it's related, but wyrms got all old statuses and then no more. The flower monitor shows there are 900 queued tasks and the number doesn't get lower while the Tasks section doesn't show any new tasks since the restart. `dc ps` says all statuses are up. `dc logs' also doesn't show anything since then. The web ui is totally responsive and doesn't show any errors though.

**Comment by mouse-reeve** [comment]
flower seems to behave poorly when there's a huge celery backlog. if things are responsive in the ui, it might be worth giving it some time to work through queued tasks?

**Comment by tofuwabohu** [comment]
I restarted celery with the `bw-dev`tool and now it seems to be working on the backlog. :)

**Comment by tofuwabohu** [comment]
Looks like everything is working again! Thanks.
