### ISSUE TITLE
Whole instance shutdown

### ISSUE THREAD

**Issue by joachimesque** [bookwyrm-social/bookwyrm#1411]
Hey,

I was on vacation so I don't know what happened, but at one point my instance crashed (error 502). I think that it's only `bookwyrm_web_1` that shut down, though I'm not sure. Here's the log right before the shutdown:

```
[2021-09-11 00:27:43 +0000] [24720] [INFO] Booting worker with pid: 24720
[2021-09-11 00:27:48 +0000] [24720] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/bookwyrm/wsgi.py", line 18, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/imagekit/__init__.py", line 3, in <module>
    from . import generatorlibrary
  File "/usr/local/lib/python3.9/site-packages/imagekit/generatorlibrary.py", line 3, in <module>
    from .specs import ImageSpec
  File "/usr/local/lib/python3.9/site-packages/imagekit/specs/__init__.py", line 4, in <module>
    from ..cachefiles.backends import get_default_cachefile_backend
  File "/usr/local/lib/python3.9/site-packages/imagekit/cachefiles/backends.py", line 143, in <module>
    from celery import task
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/usr/local/lib/python3.9/site-packages/celery/local.py", line 514, in __getattr__
    module = __import__(self._direct[name], None, None, [name])
  File "/usr/local/lib/python3.9/site-packages/celery/task/__init__.py", line 11, in <module>
    from celery._state import current_app
  File "/usr/local/lib/python3.9/site-packages/celery/_state.py", line 17, in <module>
    from celery.utils.threads import LocalStack
  File "/usr/local/lib/python3.9/site-packages/celery/utils/__init__.py", line 19, in <module>
    from .nodenames import nodename, nodesplit, worker_direct
  File "/usr/local/lib/python3.9/site-packages/celery/utils/nodenames.py", line 9, in <module>
    from kombu.entity import Exchange, Queue
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 941, in get_code
  File "<frozen importlib._bootstrap_external>", line 1040, in get_data
MemoryError
[2021-09-11 00:27:51 +0000] [24720] [INFO] Worker exiting (pid: 24720)
[2021-09-11 00:27:57 +0000] [1] [INFO] Shutting down: Master
[2021-09-11 00:27:57 +0000] [1] [INFO] Reason: Worker failed to boot.
```

I think it's a freak accident. I'll keep this issue updated if the problem pops up again.

**Comment by joachimesque** [comment]
I've since added swap on the instance's server, and the problem hasn't been back. i'll close this issue for now
