### ISSUE TITLE
Having Trouble Migrating

### ISSUE THREAD

**Issue by oragegu** [bookwyrm-social/bookwyrm#1497]
**Describe the bug**
Again, it's not precisely a bug.
```docker
    ports:
      - 5433:5432
```
The two bookwyrm instances I help adminstering they all coexist with a mastodon instance. Since both machines installed mastodon first, so I twerked the port a bit.

I have noticed that the newest docker-compose file the quoted lines are removed. Not knowing what it would do I am a bit scared to upgrade now, and would like to make sure everything will be fine before doing something reckless and losing data.

**To Reproduce**
1. Git merge on the production branch
2. Oh no connflits
3. Oh no no more `ports` under db

---
Update:

While running `docker-compose exec web python manage.py migrate`, the program exited with an error code of 1 and displayed the following error messages:
```
Operations to perform:                                                                                                                                                                                             

Apply all migrations: admin, auth, bookwyrm, contenttypes, sessions                                                                                                                                              

Running migrations:                                                                                                                                                                                                  

Applying bookwyrm.0099_readthrough_is_active... OK                                                                                                                                                                 

Applying bookwyrm.0100_shelf_description... OK                                                                                                                                                                     

Applying bookwyrm.0101_auto_20210929_1847...Traceback (most recent call last):                                                                                                                                     File "/app/manage.py", line 18, in <module>                                                                                                                                                                          

execute_from_command_line(sys.argv)                                                                                                                                                                              

File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line                                                                                          

utility.execute()                                                                                                                                                                                                

File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute                                                                                                               

self.fetch_command(subcommand).run_from_argv(self.argv)                                                                                                                                                          

File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv                                                                                                             

self.execute(*args, **cmd_options)                                                                                                                                                                               

File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute                                                                                                                   

output = self.handle(*args, **options)                                                                                                                                                                           

File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped                                                                                                                    res = 

handle_func(*args, **kwargs)                                                                                                                                                                               

File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle                                                                                                        post_migrate_state = executor.migrate(                                                                                                                                                                           

File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate                                                                                                                 

state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)                                                                                                                 

File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards                                                                                                   

state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)                                                                                                                             

File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration                                                                                                         

state = migration.apply(state, schema_editor)                                                                                                                                                                    

File "/usr/local/lib/python3.9/site-packages/django/db/migrations/migration.py", line 126, in apply                                                                                                               
operation.database_forwards(self.app_label, schema_editor, old_state, project_state)                                                                                                                             

File "/usr/local/lib/python3.9/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards                                                                                             self.code(from_state.apps, schema_editor)                                                                                                                                                                        


File "/app/bookwyrm/migrations/0101_auto_20210929_1847.py", line 20, in infer_format                                                                                                                                 edition.save(broadcast=False, update_fields=["physical_format"])                                                                                                                                               

TypeError: save() got an unexpected keyword argument 'broadcast'                                                                                                                                                   

ERROR: 1  
```

**Comment by mouse-reeve** [comment]
I removed that line because I _think_ that line wasn't actually doing anything. What's the output when you run:
``` bash
docker port bookwyrm_db_1
```

**Comment by oragegu** [comment]
> I removed that line because I _think_ that line wasn't actually doing anything. What's the output when you run:
> 
> ```shell
> docker port bookwyrm_db_1
> ```

```
5432/tcp -> 0.0.0.0:5433                                                                                                                                                                                           5432/tcp -> :::5433 
```

**Comment by mouse-reeve** [comment]
are you using the PGPORT variable in the .env file?

**Comment by oragegu** [comment]
> are you using the PGPORT variable in the .env file?

I am. And I have left the ports of db on the docker-compose.yml file.

**Comment by mouse-reeve** [comment]
okay, did that work for you to update?

**Comment by oragegu** [comment]
> okay, did that work for you to update?

What do you mean? The error happened while my variable is named PGPORT. Do you mean that I should go back to using POSTGRES_PORT?

**Comment by mouse-reeve** [comment]
Oh I see, I missed the message you posted after mine and misunderstood. No, don't go back to using the POSTGRES_PORT variable; it looks like your .env variables have the right names.

When you say you got an error, do you mean the one you posted in the original post above? `TypeError: save() got an unexpected keyword argument 'broadcast'` is my bad, and I'll fix it momentarily.

I think since you set PGPORT, the line in the docker-compose file isn't needed, but this is not my strong suit, so thank you for bearing with me

**Comment by oragegu** [comment]
> When you say you got an error, do you mean the one you posted in the original post above? 

Yes, the one all the way on the top

**Comment by mouse-reeve** [comment]
Okay, that migration should be fixed in production now

**Comment by oragegu** [comment]
> Okay, that migration should be fixed in production now

Aaand we are upgraded!

Thank you for the swift responses!
