### ISSUE TITLE
Need help in building a Bookwyrm website

### ISSUE THREAD

**Issue by Guanchishan** [bookwyrm-social/bookwyrm#1628]
I followed the guide step-by-step at https://docs.joinbookwyrm.com/installing-in-production.html ,with two slight differences.
1. I didn't set up external storage, and the relevant option in `.env` is `false`
2. my web server is Apache, so I followed the [official documentation](https://docs.joinbookwyrm.com/using-a-reverse-proxy.html)  for reverse-proxy instructions to configure
I also avoided the port conflicts, etc. From the output after typing the command, everything seems to be working fine.
But when I finally opened the set URL, it was 403.
It seems that it is difficult for me to figure out what the problem is.
But I would like to ask if Bookwyrm has any default documentation for websites (e.g. `index.html`, `index.php`, etc.) that I need to do additional settings to avoid 403?

**Comment by mouse-reeve** [comment]
Dang I'm sorry you're running into issues with this! Can you tell if the 403 error is coming from Apache or Nginx? And are there any errors in the server logs that seem meaningful? To see the nginx logs, you can run `docker-compose logs --tail=50 nginx`

**Comment by Guanchishan** [comment]
This is my website error log.
```
[Mon Nov 22 11:49:36.331728 2021] [autoindex:error] [pid 929008:tid 140550372022016] [client xx.xx.xx.xx:xx] AH01276: Cannot serve directory /path/to/website/folder/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Mon Nov 22 11:50:27.108949 2021] [autoindex:error] [pid 928758:tid 140550321665792] [client xx.xx.xx.xx:xx] AH01276: Cannot serve directory /path/to/website/folder/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Mon Nov 22 11:55:27.243074 2021] [ssl:warn] [pid 935:tid 140550797229120] AH01909: SSL.my.link:443:0 server certificate does NOT include an ID which matches the server name
[Mon Nov 22 11:55:27.445268 2021] [ssl:warn] [pid 935:tid 140550797229120] AH01909: SSL.my.link:443:0 server certificate does NOT include an ID which matches the server name
[Mon Nov 22 11:55:54.520807 2021] [ssl:warn] [pid 935:tid 140550797229120] AH01909: SSL.my.link:443:0 server certificate does NOT include an ID which matches the server name
[Mon Nov 22 11:58:05.349520 2021] [autoindex:error] [pid 930262:tid 140550422378240] [client xx.xx.xx.xx:xx] AH01276: Cannot serve directory /path/to/website/folder/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Mon Nov 22 11:58:10.705286 2021] [autoindex:error] [pid 930421:tid 140550338451200] [client xx.xx.xx.xx:xx] AH01276: Cannot serve directory /path/to/website/folder/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Mon Nov 22 11:58:19.034101 2021] [autoindex:error] [pid 930421:tid 140550330058496] [client xx.xx.xx.xx:xx] AH01276: Cannot serve directory /path/to/website/folder/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Mon Nov 22 11:58:35.630416 2021] [autoindex:error] [pid 930262:tid 140550338451200] [client xx.xx.xx.xx:xx] AH01276: Cannot serve directory /path/to/website/folder/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Mon Nov 22 11:58:45.110857 2021] [autoindex:error] [pid 930260:tid 140550455949056] [client xx.xx.xx.xx:xx] AH01276: Cannot serve directory /path/to/website/folder/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
[Mon Nov 22 11:59:43.624036 2021] [proxy_fcgi:error] [pid 930421:tid 140550553790208] [client xx.xx.xx.xx:xx] AH01071: Got error 'Primary script unknown'
[Mon Nov 22 11:59:46.509255 2021] [proxy_fcgi:error] [pid 930262:tid 140550288094976] [client xx.xx.xx.xx:xx] AH01071: Got error 'Primary script unknown'
[Mon Nov 22 12:10:08.946750 2021] [proxy_fcgi:error] [pid 930262:tid 140550422378240] [client xx.xx.xx.xx:xx] AH01071: Got error 'Primary script unknown'
[Mon Nov 22 12:10:13.857353 2021] [proxy_fcgi:error] [pid 930421:tid 140550330058496] [client xx.xx.xx.xx:xx] AH01071: Got error 'Primary script unknown'
[Mon Nov 22 12:38:25.139077 2021] [ssl:warn] [pid 935:tid 140550797229120] AH01909: SSL.my.link:443:0 server certificate does NOT include an ID which matches the server name
[Mon Nov 22 14:34:26.540230 2021] [autoindex:error] [pid 937742:tid 140550372022016] [client xx.xx.xx.xx:xx] AH01276: Cannot serve directory /path/to/website/folder/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive, referer: www.bing.com
[Mon Nov 22 14:34:30.361425 2021] [autoindex:error] [pid 937903:tid 140550380414720] [client xx.xx.xx.xx:xx] AH01276: Cannot serve directory /path/to/website/folder/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive, referer: yahoo.com
[Mon Nov 22 15:04:33.402986 2021] [autoindex:error] [pid 937903:tid 140550772000512] [client xx.xx.xx.xx:xx] AH01276: Cannot serve directory /path/to/website/folder/: No matching DirectoryIndex (index.php,index.html,index.htm,default.php,default.html,default.htm) found, and server-generated directory index forbidden by Options directive
```

**Comment by Guanchishan** [comment]
> Dang I'm sorry you're running into issues with this! Can you tell if the 403 error is coming from Apache or Nginx? And are there any errors in the server logs that seem meaningful? To see the nginx logs, you can run `docker-compose logs --tail=50 nginx`

```
Attaching to mylink_nginx_1
nginx_1           | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1           | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_1           | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_1           | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx_1           | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx_1           | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_1           | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx_1           | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_1           | 2021/11/22 15:03:10 [notice] 1#1: using the "epoll" event method
nginx_1           | 2021/11/22 15:03:10 [notice] 1#1: nginx/1.21.4
nginx_1           | 2021/11/22 15:03:10 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
nginx_1           | 2021/11/22 15:03:10 [notice] 1#1: OS: Linux 5.4.0-90-generic
nginx_1           | 2021/11/22 15:03:10 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx_1           | 2021/11/22 15:03:10 [notice] 1#1: start worker processes
nginx_1           | 2021/11/22 15:03:10 [notice] 1#1: start worker process 31
```

**Comment by mouse-reeve** [comment]
hm, it looks like the problem is with how apache is configured -- it looks like it's trying to access a static html file at a default location (`/path/to/website/folder/`), as opposed to accessing the port that BookWyrm is running on. Since BookWyrm is a dynamic app, it doesn't have an index.html type file that apache can point to. 

I don't know Apache super well, but I think you need to write a reverse proxy block -- https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html

**Comment by Guanchishan** [comment]
I am trying it. Thank you for telling me!

**Comment by Guanchishan** [comment]
I reverse proxied port `8000` to my domain and was told that there was a server error after accessing it. What should I do?
![image](https://user-images.githubusercontent.com/30859354/143446524-b8542a4c-13e0-4ca8-9f7b-ccb80d63d4ca.png)
![image](https://user-images.githubusercontent.com/30859354/143446544-d8d06aaa-1e11-4bb5-a5b1-5612b727444a.png)

**Comment by mouse-reeve** [comment]
It looks like static files aren't loading, so you may need a block in the apache config that's set up like the reverse proxy for the app but for the `/static/` and `/images/` paths. 

I'm not sure why it's getting a server error; is there anything in the web logs `docker-compose logs --tail=50 web` explaining it?

**Comment by NonSparkly** [comment]
I'm running a similar setup as you @Guanchishan but with clean ubuntu instead of apache, and I got about as far as you've done here and saw a similar layout when I spun it up and tried to access it without doing the `./bw-dev initdb` and `./bw-dev collectstatic` commands. So maybe verify that those are done? 

I also think that you should be proxying to port `8001` because that's the default port of the reverse-proxy nginx at the bottom of the production config template, no?

**Comment by Guanchishan** [comment]
I dropped the Apache server and used Nginx instead. Then when I executed `docker-compose up -d`, the nginx image did not start successfully.

I ran this command: `/bw-dev initdb`, and got the following result.

```
+ CMD=initdb
+ '[' -n initdb ']'
+ shift
+ set -x
+ case "$CMD" in
+ initdb
+ execweb python manage.py migrate
+ docker-compose exec web python manage.py migrate
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "fedireads"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/model_checks.py", line 34, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1290, in check
    *cls._check_indexes(databases),
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1682, in _check_indexes
    connection.features.supports_covering_indexes or
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/features.py", line 93, in is_postgresql_11
    return self.connection.pg_version >= 110000
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 329, in pg_version
    with self.temporary_connection():
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 603, in temporary_connection
    with self.cursor() as cursor:
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "fedireads"
```

**Comment by Guanchishan** [comment]
@mouse-reeve Thanks for answering me! 
Now I run `docker-compose logs --tail=50 web` and I get the following result.

```
Attaching to chatancc_web_1
web_1             | [2021-12-09 17:00:42 +0000] [1] [INFO] Starting gunicorn 20.0.4
web_1             | [2021-12-09 17:00:42 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
web_1             | [2021-12-09 17:00:42 +0000] [1] [INFO] Using worker: sync
web_1             | [2021-12-09 17:00:42 +0000] [7] [INFO] Booting worker with pid: 7
web_1             | [2021-12-09 17:08:46 +0000] [1] [INFO] Handling signal: term
web_1             | [2021-12-09 17:08:46 +0000] [7] [INFO] Worker exiting (pid: 7)
web_1             | [2021-12-09 17:08:47 +0000] [1] [INFO] Shutting down: Master
web_1             | [2021-12-09 18:22:42 +0000] [1] [INFO] Starting gunicorn 20.0.4
web_1             | [2021-12-09 18:22:42 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
web_1             | [2021-12-09 18:22:42 +0000] [1] [INFO] Using worker: sync
web_1             | [2021-12-09 18:22:42 +0000] [7] [INFO] Booting worker with pid: 7
```

**Comment by Guanchishan** [comment]
> Then when I executed docker-compose up -d, the nginx_1 image did not start successfully.

Now visiting the link I was expecting returns `nginx 403`. I think this is because the `nginx_1` image is not starting properly.

**Comment by mouse-reeve** [comment]
> I dropped the Apache server and used Nginx instead. Everything else is set up by following the tutorial from the beginning. Instead of using a proxy port, I used the default 80 and 443. Then when I executed `docker-compose up -d`, the `nginx_1` image did not start successfully.

Are you running nginx separately on the server? If so, the dockerized version may be failing because the ports its trying to use are already in use.

> 
> I ran this command: `/bw-dev initdb`, and got the following result.
> 
> ```
...
> django.db.utils.OperationalError: FATAL:  password authentication failed for user "fedireads"
> ```

I'm not sure why this would be happening, but I think you can fix it by setting the password in psql to the one defined in your .env file. To get into psql, `./bw-dev dbshell`, and then run `ALTER ROLE fedireads WITH PASSWORD '<yourpassword>';`

**Comment by Guanchishan** [comment]
> Are you running nginx separately on the server?

Yes, I am. Because I have another site which need to use nginx server. What do I need to do to make Bookwyrm successfully accessible to the outside world as well?

> I'm not sure why this would be happening,

No password error was encountered during the first installation. Later, reinstallations started telling me I had a wrong db password. Maybe the previous installation resulted in some residual files.

**Comment by Guanchishan** [comment]
Can the database name and database username in the `.env` file be changed to something other than `fedireads`? Or the name must be `fedireads`, otherwise the program will run wrong?

**Comment by mouse-reeve** [comment]
It may be residual files. And yes, you should be able to change the database name.

You'll need to change the port in the docker nginx config so that it isn't trying to use the same port at the nginx on your server -- in the example in the production nginx file, it looks like this:
```
# Reverse-Proxy server
 server {
     listen [::]:8001;
     listen 8001;

     server_name your-domain.com www.your-domain.com;

     location / {
         proxy_pass http://web;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header Host $host;
         proxy_redirect off;
     }

     location /images/ {
         alias /app/images/;
     }

     location /static/ {
         alias /app/static/;
     }
}
```

**Comment by Guanchishan** [comment]
> You'll need to change the port in the docker nginx config so that it isn't trying to use the same port at the nginx on your server -- in the example in the production nginx file, it looks like this:

Do you mean that I should enable Reverse-Proxy server and close the default ports 80 and 443?

**Comment by Guanchishan** [comment]
I changed the database name in `.env`, but I still encountered the problem of wrong database password. When I run `. /bw-dev initdb` and then:

```
+ CMD=initdb
+ '[' -n initdb ']'
+ shift
+ set -x
+ case "$CMD" in
+ initdb
+ execweb python manage.py migrate
+ docker-compose exec web python manage.py migrate
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "newname"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/model_checks.py", line 34, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1290, in check
    *cls._check_indexes(databases),
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1682, in _check_indexes
    connection.features.supports_covering_indexes or
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/features.py", line 93, in is_postgresql_11
    return self.connection.pg_version >= 110000
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 329, in pg_version
    with self.temporary_connection():
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 603, in temporary_connection
    with self.cursor() as cursor:
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "newname"
```

I try to set up a reverse proxy and it returns an error: `Internal Server Error`

![企业微信截图_16393124678756](https://user-images.githubusercontent.com/30859354/145712445-cabe764f-39c2-4ccc-a8c5-c617da474b4f.png)

**Comment by Guanchishan** [comment]
I'm not going to create a new Bookwyrm site for a while, so I'm closing this issue, but thank you all so much for answering my questions.
