### ISSUE TITLE
Invalid table limit error

### ISSUE THREAD

**Issue by hughrun** [bookwyrm-social/bookwyrm#1861]
**Describe the bug**
When running a fresh dev instance I get an `Invalid table limit` error, coming from `initdb.py`. Not sure if something is broken in the latest main branch, or I need to update my configuration.

**To Reproduce**
1. fetch latest `main` branch
2. `./bw-dev resetdb`
3. Get error (see below)

**Expected behavior**
BookWyrm resets database and new install works without errors.

**Screenshots**
```
  Applying sessions.0001_initial... OK
+ execweb python manage.py initdb
+ docker-compose exec web python manage.py initdb
Traceback (most recent call last):
  File "/app/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/app/bookwyrm/management/commands/initdb.py", line 168, in handle
    raise Exception("Invalid table limit:", limit)
Exception: ('Invalid table limit:', None)
```

**Instance**
local development, current `main` branch.

**Additional context**
I initially started getting this error on a branch I was working on, but it's occuring on the latest `main` branch without any changes.

---

**Desktop (please complete the following information):**
    - OS: MacOS

**Comment by mouse-reeve** [comment]
Oh! I broke this when I updated the management command to take options.
