### ISSUE TITLE
Exception resolving a bunch of template variables

### ISSUE THREAD

**Issue by cincodenada** [bookwyrm-social/bookwyrm#1906]
**Describe the bug**

After upgrading, I get a ton of errors similar to the following. Things seem to work, but they're very slow:

```
Exception while resolving variable 'title' in template 'book/editions/editions.html'.
web_1             | Traceback (most recent call last):
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 829, in _resolve_lookup
web_1             |     current = current[bit]
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
web_1             |     raise KeyError(key)
web_1             | KeyError: 'title'
web_1             | 
web_1             | During handling of the above exception, another exception occurred:
web_1             | 
web_1             | Traceback (most recent call last):
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 835, in _resolve_lookup
web_1             |     if isinstance(current, BaseContext) and getattr(type(current), bit):
web_1             | AttributeError: type object 'RequestContext' has no attribute 'title'
web_1             | 
web_1             | During handling of the above exception, another exception occurred:
web_1             | 
web_1             | Traceback (most recent call last):
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 843, in _resolve_lookup
web_1             |     current = current[int(bit)]
web_1             | ValueError: invalid literal for int() with base 10: 'title'
web_1             | 
web_1             | During handling of the above exception, another exception occurred:
web_1             | 
web_1             | Traceback (most recent call last):
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 848, in _resolve_lookup
web_1             |     raise VariableDoesNotExist("Failed lookup for key "
web_1             | django.template.base.VariableDoesNotExist: Failed lookup for key [title] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fba91824f70>>, 'request': <WSGIRequest: GET '/book/12354/editions'>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7fba918af520>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fba90f64790>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fba91982ac0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'site': <SiteSettings: SiteSettings object (1)>, 'active_announcements': <QuerySet []>, 'thumbnail_generation_enabled': True, 'media_full_url': 'https://bookwyrm.s3.us-west-004.backblazeb2.com/images/', 'preview_images_enabled': False, 'request_protocol': 'http://', 'js_cache': '7b5303af'}, {}, {'editions': <Page 1 of 1>, 'work': <<class 'bookwyrm.models.book.Work'> key='OL4321141W' title='The secret history'>, 'languages': {'Dutch', 'German', 'English'}, 'formats': {'hardcover', 'paperback'}}]
web_1             | Exception while resolving variable 'title' in template 'book/editions/editions.html'.
web_1             | Traceback (most recent call last):
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 829, in _resolve_lookup
web_1             |     current = current[bit]
web_1             |   File "/usr/local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
web_1             |     raise KeyError(key)
web_1             | KeyError: 'title'
```

**To Reproduce**
1. Upgrade to the latest production
2. Set `LOG_LEVEL=debug` in your `.env`
3. `./bw-dev up -d`
2. Tail the web logs
3. Load the main page

**Expected behavior**
It's not full of errors

**Instance**
bookwyrm.cincodenada.com

**Comment by cincodenada** [comment]
After some more testing here, I think I'm the only one seeing this because it only happens (or shows up, at least) if you have `LOG_LEVEL=debug` in your `.env` - so, this is less critical than I feared.

That also raises the question of, is the logging causing the errors, or is it just showing errors that were already happening? It seems strange that exceptions wouldn't be logged under the default level, but who knows. I'll have to dig into this more when I'm more awake, ha.

But anyway, if you're also seeing this, setting `LOG_LEVEL` to `info` (and running `./bw-dev up -d` to rebuild the images) seems to fix it as well.
