### ISSUE TITLE
Can not get admin_code

### ISSUE THREAD

**Issue by jaschaurbach** [bookwyrm-social/bookwyrm#2347]
**Describe the bug**
I followed the instructions of https://docs.joinbookwyrm.com/install-prod-dockerless.html
running "python manage.py admin_code" fails with

```
*******************************************
Use this code to create your admin account:
Traceback (most recent call last):
  File "/home/wyrm/bookwyrm/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/home/wyrm/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/wyrm/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/wyrm/.local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/wyrm/.local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/wyrm/bookwyrm/bookwyrm/management/commands/admin_code.py", line 22, in handle
    self.stdout.write(get_admin_code())
  File "/home/wyrm/bookwyrm/bookwyrm/management/commands/admin_code.py", line 9, in get_admin_code
    return models.SiteSettings.objects.get().admin_code
  File "/home/wyrm/.local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/wyrm/.local/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
bookwyrm.models.site.SiteSettings.DoesNotExist: SiteSettings matching query does not exist.
```

**Expected behavior**
Getting an admin code

**Screenshots**
n/a
**Instance**
none as it does not run

**Additional context**
n/a

**Comment by mouse-reeve** [comment]
It looks like there's a step missing from the instructions to initialize the database. You should be able to fix the issue by running `python manage.py initdb`

**Comment by mouse-reeve** [comment]
You may also need to run `python manage.py migrate` 🤔

**Comment by jaschaurbach** [comment]
I ran the migration but yeah, there is no `python manage.py initdb` in the instruction. So, once again, going to install bookwyrm. Let's see if it works :)

**Comment by jaschaurbach** [comment]
in fact in the instruction there is only: 

Initialize the database by running venv/bin/python3 manage.py migrate. Where should I do initdb? I am not that familiar with Django or postgres

**Comment by mouse-reeve** [comment]
You can run it the same way you ran the migrate command: `venv/bin/python3 manage.py initdb`

**Comment by jaschaurbach** [comment]
Sorry, was unclear - when in the setup process should it be run. Before the migrations?

**Comment by mouse-reeve** [comment]
Oh I see - you should run it after the migrations. But I noticed that migrations are in the steps, so if you already ran them you won't need to again.

**Comment by jaschaurbach** [comment]
Thanks, I got it so far, now I am running in other issues which are not caused by bookwyrm but by Django, gunicorn, supervisord and the never ending story of serving statistics :D 

I close this issue, thank you for your help so far.
