### ISSUE TITLE
Internal Server Errors (e.g. on delete of user)

### ISSUE THREAD

**Issue by marcusyoung** [bookwyrm-social/bookwyrm#2348]
**Describe the bug**
Internal server error for some actions. I have set up a dockerless  installation and am able to access the application and the admin pages. However, some actions create errors.  For example: 

**To Reproduce**
1. Clicking delete user after providing admin password. Browser shows internal server error. Error in application is:

```
Internal Server Error: /settings/reports/2/delete
Traceback (most recent call last):
  File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/template/response.py", line 65, in resolve_template
    return get_template(template, using=self.using)
  File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: user_admin/user.html
```

**Comment by mouse-reeve** [comment]
This is a silly error on my part -- I need to write a unit test as well as fix it. It's just the wrong template path. Thank you!
