### ISSUE TITLE
Server error on some book imports

### ISSUE THREAD

**Issue by marcusyoung** [bookwyrm-social/bookwyrm#2350]
**Describe the bug**
When importing some books the application crashes, with "Server Error Something went wrong! Sorry about that."
```
Internal Server Error: /resolve-book
Traceback (most recent call last):
  File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/bookwyrm/venv/lib/python3.10/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/opt/bookwyrm/bookwyrm/views/books/books.py", line 190, in resolve_book
    return redirect("book", book.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by marcusyoung** [comment]
This does seem a bit random. Sometimes a particular book will cause it but then try again with the same book and it works.

**Comment by biglifedecision** [comment]
I have the same error (with the aforementioned specific book as an example, https://inventaire.io/entity/wd:Q3294970

the book is apparently successfully imported, despite the error page. it can be found in the bookwyrm instance later as an imported book. had this happen with several inventaire imports, but not any others (out of maybe 10 or so)
