### ISSUE TITLE
./bw-dev stylelint throws error

### ISSUE THREAD

**Issue by jaschaurbach** [bookwyrm-social/bookwyrm#2530]
`./bw-dev stylelint`

```
Need to install the following packages:
  stylelint@14.16.0
Ok to proceed? (y) y
Error: Could not find "stylelint-config-standard". Do you need a `configBasedir`?
    at configurationError (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/utils/configurationError.js:11:49)
    at getModulePath (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/utils/getModulePath.js:28:9)
    at loadExtendedConfig (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/augmentConfig.js:236:21)
    at extendConfig (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/augmentConfig.js:207:30)
    at augmentConfigBasic (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/augmentConfig.js:52:26)
    at augmentConfigFull (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/augmentConfig.js:106:30)
    at Object.transform (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/getConfigForFile.js:51:37)
    at runLoad (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/cosmiconfig/dist/Explorer.js:104:49)
    at async cacheWrapper (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/cosmiconfig/dist/cacheWrapper.js:16:18)
    at async getConfigForFile (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/getConfigForFile.js:56:5)
```

**Comment by mouse-reeve** [comment]
Related: https://github.com/bookwyrm-social/bookwyrm/pull/2032

**Comment by mouse-reeve** [comment]
Closing this because it's very old
