### ISSUE TITLE
HTTP 502 error when importing book from remote BookWyrm instance

### ISSUE THREAD

**Issue by hueyy** [bookwyrm-social/bookwyrm#2650]
**Describe the bug**
When importing a book from a remote BookWyrm instance, a HTTP 502 error is sometimes thrown.

**To Reproduce**
1. Search for a book (e.g. "Don't Sleep, There Are Snakes")
2. Click the import button to import it from a remote BookWyrm instance
3. A HTTP 502 error is thrown

The logs for the bookwyrm_web Docker instance during the import are as follows:

```
Cannot connect to host bookwyrm.pt:443 ssl:default [Name or service not known]
Unable to connect to https://books.meowy.tech/search?q=Don't Sleep, There Are Snakes: Bad Gateway
Not Found: /api/statusnet/version.json
Not Found: /api/gnusocial/version.json
Not Found: /siteinfo.json
Not Found: /api/statusnet/config.json
Not Found: /statistics.json
Not Found: /friendica/json
Not Found: /friendika/json
[2023-02-01 02:57:30 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:7)
[2023-02-01 02:57:31 +0000] [7] [INFO] Worker exiting (pid: 7)
[2023-02-01 02:57:31 +0000] [60] [INFO] Booting worker with pid: 60
```

**Expected behavior**
The book should be imported on the first try, or an error message should be displayed if this is not possible.

**Additional context**

Occasionally, the import succeeds on the second or subsequent try (when I refresh the page and therefore resubmit the POST request). However, a different issue then arises. When I try to add the newly-imported book to a shelf, an error message ("Error posting status") is displayed (see screenshot below with error message at bottom right corner).

![2023-02-01_02-57](https://user-images.githubusercontent.com/6523121/216743726-f4922a56-8331-4367-8aa4-c2b2088da542.jpg)

The logs for the bookwyrm_web Docker instance at that time are as follows:

```
Internal Server Error: /reading-status/want/38248
Traceback (most recent call last):
  File "/app/bookwyrm/activitypub/base_activity.py", line 69, in __init__
    value = kwargs[field.name]
KeyError: 'book'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/app/bookwyrm/views/reading.py", line 91, in post
    models.ShelfBook.objects.create(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/bookwyrm/models/shelf.py", line 114, in save
    super().save(*args, priority=priority, **kwargs)
  File "/app/bookwyrm/models/activitypub_mixin.py", line 413, in save
    activity = self.to_add_activity(self.user)
  File "/app/bookwyrm/models/activitypub_mixin.py", line 429, in to_add_activity
    object=self.to_activity_dataclass(),
  File "/app/bookwyrm/models/activitypub_mixin.py", line 191, in to_activity_dataclass
    return self.activity_serializer(**activity)
  File "/app/bookwyrm/activitypub/base_activity.py", line 90, in __init__
    raise ActivitySerializerError(
bookwyrm.activitypub.base_activity.ActivitySerializerError: Missing required field: book
```

Interestingly, if I edit the book and save, I can then add the book to a shelf without any further issues.

**Additional information**

The BookWyrm instance I am using is on v0.5.4, running via docker-compose.

**Comment by mouse-reeve** [comment]
Closing this because it's very old
