### ISSUE TITLE
ModuleNotFoundError: No module named 'pyotp'

### ISSUE THREAD

**Issue by rickcecil** [bookwyrm-social/bookwyrm#2943]
**Describe the bug**
Setup: Docker, production, fresh install
OS: Ubuntu 22.10

When I run ./bw-dev migrate, I get the following:
```
+ case "$CMD" in
+ migrate
+ runweb python manage.py migrate
+ docker compose run --rm web python manage.py migrate
[+] Running 3/0
 ⠿ Container bookwyrm-redis_broker-1    Running                                                                                                                            0.0s
 ⠿ Container bookwyrm-db-1              Running                                                                                                                            0.0s
 ⠿ Container bookwyrm-redis_activity-1  Running                                                                                                                            0.0s
[+] Running 1/0
 ⠿ Container bookwyrm-celery_worker-1  Started                                                                                                                             0.0s
Traceback (most recent call last):
  File "/app/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/bookwyrm/urls.py", line 7, in <module>
    from bookwyrm import settings, views
  File "/app/bookwyrm/views/__init__.py", line 3, in <module>
    from .admin.announcements import Announcements, Announcement
  File "/app/bookwyrm/views/admin/announcements.py", line 9, in <module>
    from bookwyrm import forms, models
  File "/app/bookwyrm/forms/__init__.py", line 9, in <module>
    from .landing import *
  File "/app/bookwyrm/forms/landing.py", line 7, in <module>
    import pyotp
ModuleNotFoundError: No module named 'pyotp'
```

I have done everything that I can think to do to make sure pyopt is installed. I have installed it in every version of python on my computer and have made sure it is in the path. I am honestly not sure what else to do.

**Comment by hughrun** [comment]
I'm wondering if the instructions need to be amended.

Can you try running `./bw-dev build` before you run the `migrate` command?

**Comment by mouse-reeve** [comment]
Is it possible that `pyopt` is installed on your local machine but not in docker? You should be able to see what's installed with `docker-compose run --rm celery_worker pip freeze`. I would expect running `docker-compose build celery_worker` would fix this by installing all the necessary packages, but `./bw-dev build` (which will build all images) would be a better bet since if this one isn't built properly, they others may not be either.

**Comment by rickcecil** [comment]
That worked. pyotp was not installed in docker. 

But now I am running into a separate issue -- not sure if they are related. 

```
connection to server at "db" (#.#.#.#), port 5432 failed: FATAL:  password authentication failed for user "myusername"
```

I've tried

```
./bw-dev migrate
./bw-dev build
./bw-dev initdb
docker-compose -- build
```

I even tried connecting to the database to create a db user as suggested here:
https://github.com/bookwyrm-social/bookwyrm/issues/2001#issuecomment-1065580536

I am running behind a reverse proxy and followed the instructions here:
https://docs.joinbookwyrm.com/reverse-proxy.html

(Though I am confused why the nginx port doesn't match the web service port on the docker side.)

TIA for any additional support!

**Comment by hughrun** [comment]
@rickcecil is this a completely fresh install/db? I think you might have missed some setup.

The usual order would be:

```
./bw-dev build
./bw-dev setup
docker compose up -d
```
`setup` will take care of `initdb` and `migrate`.

**Comment by hughrun** [comment]
closing as stale
