### ISSUE TITLE
bw-dev stylelint cannot be run

### ISSUE THREAD

**Issue by skmanohar** [bookwyrm-social/bookwyrm#3031]
**Describe the bug**
1. `./bw-dev stylelint` cannot be run

**To Reproduce**
1. Run `./bw-dev stylelint` on main

```sh
Error: Could not find "stylelint-config-standard". Do you need the "configBasedir" or "--config-basedir" option?
    at configurationError (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/utils/configurationError.js:12:49)
    at getModulePath (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/utils/getModulePath.js:28:9)
    at loadExtendedConfig (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/augmentConfig.js:216:21)
    at extendConfig (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/augmentConfig.js:184:25)
    at augmentConfigBasic (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/augmentConfig.js:57:26)
    at augmentConfigFull (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/augmentConfig.js:111:30)
    at Object.transform (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/getConfigForFile.js:51:37)
    at load (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/cosmiconfig/dist/Explorer.js:20:38)
    at async Explorer.load (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/cosmiconfig/dist/Explorer.js:23:20)
    at async getConfigForFile (/root/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/getConfigForFile.js:61:5)

```

**Expected behavior**
stylelint should run without errors

---

**Desktop (please complete the following information):**
    - OS: Windows, using git-bash

**Comment by jaschaurbach** [comment]
I found it!

running .`/bw-dev build` builds (besides others) the `dev-tools` container. The way we install node is deprecated

```
=> [7/9] RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -                                                                             8.1s 
 => => #                           SCRIPT DEPRECATION WARNING                                                                                          
 => => # ================================================================================                                                              
 => => # ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓                                                              
 => => # ================================================================================                                                              
 => => # TO AVOID THIS WAIT MIGRATE THE SCRIPT                                                                                                         
 => => # Continuing in 60 seconds (press Ctrl-C to abort) ...                                                                                         
```

later in the build process is another error:

```
 > [9/9] RUN npm install .:                                                                                                                            
#0 2.657 npm notice                                                                                                                                    
#0 2.657 npm notice New major version of npm available! 9.6.7 -> 10.2.0                                                                                
#0 2.658 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.0>                                                                       
#0 2.658 npm notice Run `npm install -g npm@10.2.0` to update!
#0 2.658 npm notice 
#0 2.662 npm ERR! code ERESOLVE
#0 2.669 npm ERR! ERESOLVE unable to resolve dependency tree
#0 2.669 npm ERR! 
#0 2.670 npm ERR! While resolving: undefined@undefined
#0 2.670 npm ERR! Found: stylelint@15.10.2
#0 2.670 npm ERR! node_modules/stylelint
#0 2.670 npm ERR!   dev stylelint@"15.10.2" from the root project
#0 2.670 npm ERR! 
#0 2.670 npm ERR! Could not resolve dependency:
#0 2.670 npm ERR! peer stylelint@"^14.4.0" from stylelint-config-recommended@7.0.0
#0 2.670 npm ERR! node_modules/stylelint-config-recommended
#0 2.670 npm ERR!   dev stylelint-config-recommended@"^7.0.0" from the root project
#0 2.670 npm ERR! 
#0 2.670 npm ERR! Fix the upstream dependency conflict, or retry
#0 2.670 npm ERR! this command with --force or --legacy-peer-deps
#0 2.670 npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I conclude our dependencies are broken.
