### ISSUE TITLE
Error in bookwyrm.suggested_users.remove_user_task

### ISSUE THREAD

**Issue by prolibre** [bookwyrm-social/bookwyrm#3259]
_Bookwyrm 0.7.1_

I've noticed quite a few errors with the bookwyrm.suggested_users.remove_user_task task

If I look for the id ('args') transmitted I see that it corresponds to an entry in the 'bookwyrm_user' table

```
Traceback (most recent call last):
  File "/opt/bookwyrm/venv/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/opt/bookwyrm/venv/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bookwyrm/bookwyrm/suggested_users.py", line 271, in remove_user_task
    user = models.User.objects.get(id=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bookwyrm/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bookwyrm/venv/lib/python3.11/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
bookwyrm.models.user.User.DoesNotExist: User matching query does not exist.
```

Have a nice day,

Anthony

**Comment by mouse-reeve** [comment]
Sometimes this happens when a database transaction isn't completed when the task executes. I think this can be avoided by using `on_commit`, for example: https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/suggested_users.py#L210; I think if we used this pattern here: https://github.com/bookwyrm-social/bookwyrm/blob/main/bookwyrm/suggested_users.py#L220 that would hopefully fix this?
