### ISSUE TITLE
ActivitySerializerError('No model found for activity type "Question"')

### ISSUE THREAD

**Issue by prolibre** [bookwyrm-social/bookwyrm#3349]
I think it's a minor bug of no consequence.
Via Flower I see this error from time to time.

Software version : 0.7.3 (without docker)

**args**
```
({'@context': 'https://www.w3.org/ns/activitystreams', 'id': 'https://domain2/users/user2/statuses/112219062248422324/activity', 'type': 'Announce', 'actor': 'https://domain2/users/user2', 'published': '2024-04-05T14:23:19Z', 'to': ['https://www.w3.org/ns/activitystreams#Public'], 'cc': ['https://domain1.ca/users/user1', 'https://domain2/users/user2/followers'], 'object': 'https://domain1.ca/users/user1/statuses/112215329504207846'},)
```
**Traceback** 
```
Traceback (most recent call last):
  File "/opt/bookwyrm/venv/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/opt/bookwyrm/venv/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bookwyrm/bookwyrm/views/inbox.py", line 121, in activity_task
    activity.action()
  File "/opt/bookwyrm/bookwyrm/activitypub/verbs.py", line 243, in action
    self.to_model(allow_external_connections=allow_external_connections)
  File "/opt/bookwyrm/bookwyrm/activitypub/base_activity.py", line 143, in to_model
    and model.ignore_activity(self, allow_external_connections)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bookwyrm/bookwyrm/models/status.py", line 131, in ignore_activity
    boosted = activitypub.resolve_remote_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bookwyrm/bookwyrm/activitypub/base_activity.py", line 383, in resolve_remote_id
    model = get_model_from_type(data.get("type"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bookwyrm/bookwyrm/activitypub/base_activity.py", line 305, in get_model_from_type
    raise ActivitySerializerError(
bookwyrm.activitypub.base_activity.ActivitySerializerError: No model found for activity type "Question"
```
Have a nice day,

Anthony

**Comment by mouse-reeve** [comment]
This isn't really a bug -- we don't support polls, so it's just logging that it doesn't know what that is. I had it logging because ages ago I needed it for debugging cases where activitypub types we *should* support were having issues, but we should probably reduce this to a warning or info

**Comment by prolibre** [comment]
I'm closing this alert. No need to clutter up the "issues".
