### ISSUE TITLE
Error DuplicateTable on ./bw-dev migrate command

### ISSUE THREAD

**Issue by winterjodi** [bookwyrm-social/bookwyrm#3409]
**Describe the bug**
During the installation of a new Bookwyrm instance, from the production branch, following the instructions detailed here: https://docs.joinbookwyrm.com/install-prod.html. I ran the command `./bw-dev migrate`, and it failed with the error `django.db.utils.ProgrammingError: relation "bookwyrm_tag"` already exists.

**To Reproduce**
1. Clone repository and checkout production branch.
2. Copy and modify .env file
3. Copy and modify nginx/default.conf
4. Run command `./bw-dev migrate`
5. Error returned:

> + case "$CMD" in
> + migrate
> + runweb python manage.py migrate
> + docker compose run --rm web python manage.py migrate
> WARN[0000] /home/user/bookwyrm/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
> [+] Running 9/9
>  ✔ redis_broker Pulled                                                                    5.9s 
>    ✔ a378f10b3218 Pull complete                                                           2.4s 
>    ✔ 3c75410c1f8b Pull complete                                                           2.4s 
>    ✔ 667874757cc1 Pull complete                                                           2.5s 
>    ✔ 7150b93d249d Pull complete                                                           3.7s 
>    ✔ ed7c83735e28 Pull complete                                                           3.7s 
>    ✔ 4f4fb700ef54 Pull complete                                                           3.7s 
>    ✔ 3fa899a007ab Pull complete                                                           3.7s 
>  ✔ redis_activity Pulled                                                                  5.9s 
> [+] Building 99.6s (30/30) FINISHED                                             docker:default
>  => [db internal] load build definition from Dockerfile                                   0.0s
>  => => transferring dockerfile: 1.18kB                                                    0.0s
>  => [db internal] load metadata for docker.io/library/postgres:13.0                       1.2s
>  => [db internal] load .dockerignore                                                      0.0s
>  => => transferring context: 2B                                                           0.0s
>  => [db  1/12] FROM docker.io/library/postgres:13.0@sha256:8f7c3c9b61d82a4a021da5d9618fa  7.7s
>  => => resolve docker.io/library/postgres:13.0@sha256:8f7c3c9b61d82a4a021da5d9618faf0566  0.0s
>  => => sha256:8f7c3c9b61d82a4a021da5d9618faf056633e089302a726d619fa467c7 1.86kB / 1.86kB  0.0s
>  => => sha256:e3dc51fa2b560b7daf34aa4c2501941b4ce0d701c4ecf571777b13d795 4.18MB / 4.18MB  0.4s
>  => => sha256:f213b6f96d81fa40e97b4eb61a159f716d77a4c70a25f376525385d783 1.77kB / 1.77kB  0.3s
>  => => sha256:832e01fa055c55a9c9195db231cf3935a81b7b60c8cccd64e7b5395d1e 3.25kB / 3.25kB  0.0s
>  => => sha256:c96f8b6bc0d9f0277f118cf485a8c302e32cfe05e7d65f6e9a4c1066 10.71kB / 10.71kB  0.0s
>  => => sha256:bb79b6b2107fea8e8a47133a660b78e3a546998fcf0427be39ac9a0a 27.09MB / 27.09MB  0.3s
>  => => extracting sha256:bb79b6b2107fea8e8a47133a660b78e3a546998fcf0427be39ac9a0af4a97e9  2.1s
>  => => sha256:2780ac832fdea1b95491eaf082507289c13fc77e97de2716ee80e851cc 1.42MB / 1.42MB  0.5s
>  => => sha256:95db3c06319e21f4c21eff545348f1755e5979d63c551a5b82bf9f 391.05kB / 391.05kB  0.6s
>  => => sha256:ae5cee1a3f123d23889bfdd0941b304d3906c90e136ec0e13f340b4730 7.96MB / 7.96MB  0.6s
>  => => sha256:8d602872ecaeaf9c80cc4728578cc9a9b42d53b5f9351195a60f0be445 3.05kB / 3.05kB  0.7s
>  => => sha256:475ca72764d52e2efe3b99160dbf36815c6be1ffda0790cc7e22354796185f 115B / 115B  0.7s
>  => => sha256:c4fca31f2e3d83c36758a751e320fd26cb77d6f17a5f07b73989d935 73.66MB / 73.66MB  1.3s
>  => => sha256:a00c442835e0871a8bcee1d389c603ff88190004b04ab5186d59836f2c 9.27kB / 9.27kB  0.8s
>  => => sha256:2e2305af339024dfd3d40697adb93e5ccb8decba5337e3eef1979ee4a2f151 129B / 129B  0.9s
>  => => sha256:6cff852bb872a5b4dd86f2528157acb8c3ab2f59f5bce84a91e38990afb7e7 169B / 169B  1.0s
>  => => sha256:25bb0be115435b86fab9f9ac77ee9b01ca697d631038ff6e062ff203ba 4.26kB / 4.26kB  1.0s
>  => => sha256:4738c099c4ad0480a6ea8a835aaf6777de42ec140984844cd53b9e05f8c440 121B / 121B  1.2s
>  => => extracting sha256:e3dc51fa2b560b7daf34aa4c2501941b4ce0d701c4ecf571777b13d79561f1b  0.3s
>  => => extracting sha256:f213b6f96d81fa40e97b4eb61a159f716d77a4c70a25f376525385d7836bdee  0.0s
>  => => extracting sha256:2780ac832fdea1b95491eaf082507289c13fc77e97de2716ee80e851cce0c79  0.1s
>  => => extracting sha256:ae5cee1a3f123d23889bfdd0941b304d3906c90e136ec0e13f340b473096902  0.4s
>  => => extracting sha256:95db3c06319e21f4c21eff545348f1755e5979d63c551a5b82bf9ff55ef30fa  0.0s
>  => => extracting sha256:475ca72764d52e2efe3b99160dbf36815c6be1ffda0790cc7e22354796185f0  0.0s
>  => => extracting sha256:8d602872ecaeaf9c80cc4728578cc9a9b42d53b5f9351195a60f0be4455f99f  0.0s
>  => => extracting sha256:c4fca31f2e3d83c36758a751e320fd26cb77d6f17a5f07b73989d935ddbfd51  3.6s
>  => => extracting sha256:a00c442835e0871a8bcee1d389c603ff88190004b04ab5186d59836f2c3379e  0.0s
>  => => extracting sha256:2e2305af339024dfd3d40697adb93e5ccb8decba5337e3eef1979ee4a2f151c  0.0s
>  => => extracting sha256:6cff852bb872a5b4dd86f2528157acb8c3ab2f59f5bce84a91e38990afb7e79  0.0s
>  => => extracting sha256:25bb0be115435b86fab9f9ac77ee9b01ca697d631038ff6e062ff203baf0a1f  0.0s
>  => => extracting sha256:4738c099c4ad0480a6ea8a835aaf6777de42ec140984844cd53b9e05f8c4400  0.0s
>  => [db internal] load build context                                                      0.0s
>  => => transferring context: 6.62kB                                                       0.0s
>  => [db  2/12] RUN mkdir /backups                                                         0.6s
>  => [db  3/12] COPY ./backup.sh /usr/local/bin/bookwyrm-backup.sh                         0.0s
>  => [db  4/12] COPY ./weed.sh /usr/local/bin/bookwyrm-weed.sh                             0.0s
>  => [db  5/12] COPY ./cronfile /etc/cron.d/cronfile                                       0.0s
>  => [db  6/12] RUN apt-get update && apt-get -y --no-install-recommends install cron      6.1s
>  => [db  7/12] RUN chmod 0644 /etc/cron.d/cronfile                                        0.3s
>  => [db  8/12] RUN crontab /etc/cron.d/cronfile                                           0.3s
>  => [db  9/12] RUN touch /var/log/cron.log                                                0.3s
>  => [db 10/12] RUN awk '$0 ~ /^\t_main "\$@"$/ { print "\tif [[ $1 == cron ]]; then\n\t\  0.3s
>  => [db 11/12] RUN chown postgres /bookwyrm-entrypoint.sh                                 0.3s
>  => [db 12/12] RUN chmod u=rwx,go=r /bookwyrm-entrypoint.sh                               0.2s
>  => [db] exporting to image                                                               0.2s
>  => => exporting layers                                                                   0.2s
>  => => writing image sha256:a4fc89f1717b058c708b59b7539c138a24a469f09127853fafba0e80062b  0.0s
>  => => naming to docker.io/library/bookwyrm-db                                            0.0s
>  => [db] resolving provenance for metadata file                                           0.0s
>  => [celery_worker internal] load build definition from Dockerfile                        0.0s
>  => => transferring dockerfile: 303B                                                      0.0s
>  => [celery_worker internal] load metadata for docker.io/library/python:3.11              1.0s
>  => [celery_worker internal] load .dockerignore                                           0.0s
>  => => transferring context: 97B                                                          0.0s
>  => [celery_worker 1/6] FROM docker.io/library/python:3.11@sha256:38b425945de90afd3c915  22.9s
>  => => resolve docker.io/library/python:3.11@sha256:38b425945de90afd3c9159309bda02bef439  0.0s
>  => => sha256:4b15001a996e6df687bda4eb74fad3154bdd219395acf6af22a44b79cc 2.52kB / 2.52kB  0.0s
>  => => sha256:ca4e5d6727252f0dbc207fbf283cb95e278bf562bda42d35ce6c9195 49.55MB / 49.55MB  0.5s
>  => => sha256:10d643a5fa823cd013a108b2076f4d2edf1b2a921f863b533e83ea5e 64.14MB / 64.14MB  1.2s
>  => => sha256:38b425945de90afd3c9159309bda02bef439a3331ee8b9f1a86b0edba3 9.72kB / 9.72kB  0.0s
>  => => sha256:1d837a33b98528d8235aaafd5b2df4206b896505063540ea8f43626e4c 7.32kB / 7.32kB  0.0s
>  => => sha256:30b93c12a9c9326732b35d9e3ebe57148abe33f8fa6e25ab76867410 24.05MB / 24.05MB  0.6s
>  => => sha256:d6dc1019d7935fe82827434da11bf96cf14e24979f8155e73b7942 211.24MB / 211.24MB  2.7s
>  => => sha256:b7f9990a563bce146786660fca293b52cda372129c732ec2aeb90a920c 6.16MB / 6.16MB  0.9s
>  => => extracting sha256:ca4e5d6727252f0dbc207fbf283cb95e278bf562bda42d35ce6c919583a110a  4.2s
>  => => sha256:1f8a8ef5a1663d49109f7eac520a44393d868a680a7307792144f3ee 19.84MB / 19.84MB  1.4s
>  => => sha256:6ee63fd11ef3813bf567b26b68481786c9252b242c7cafbbfd542f7829425c 232B / 232B  1.3s
>  => => sha256:45a53ad401547928304d1361a69080539b11f1a1b14066ceecc1d62570 3.13MB / 3.13MB  1.6s
>  => => extracting sha256:30b93c12a9c9326732b35d9e3ebe57148abe33f8fa6e25ab76867410b0ccf87  0.9s
>  => => extracting sha256:10d643a5fa823cd013a108b2076f4d2edf1b2a921f863b533e83ea5ed8d09bd  3.6s
>  => => extracting sha256:d6dc1019d7935fe82827434da11bf96cf14e24979f8155e73b794286f10b7f  10.6s
>  => => extracting sha256:b7f9990a563bce146786660fca293b52cda372129c732ec2aeb90a920c6fb2c  0.5s
>  => => extracting sha256:1f8a8ef5a1663d49109f7eac520a44393d868a680a7307792144f3ee7005801  1.0s
>  => => extracting sha256:6ee63fd11ef3813bf567b26b68481786c9252b242c7cafbbfd542f7829425c0  0.0s
>  => => extracting sha256:45a53ad401547928304d1361a69080539b11f1a1b14066ceecc1d625705f8bc  0.3s
>  => [celery_worker internal] load build context                                           0.0s
>  => => transferring context: 1.15kB                                                       0.0s
>  => [celery_worker 2/6] RUN mkdir /app /app/static /app/images                            0.5s
>  => [celery_worker 3/6] WORKDIR /app                                                      0.0s
>  => [celery_worker 4/6] RUN apt-get update && apt-get install -y gettext libgettextpo-de  5.5s
>  => [celery_worker 5/6] COPY requirements.txt /app/                                       0.1s
>  => [celery_worker 6/6] RUN pip install -r requirements.txt --no-cache-dir               47.4s
>  => [celery_worker] exporting to image                                                    4.3s
>  => => exporting layers                                                                   4.2s
>  => => writing image sha256:7df44830792f5e6241fa424f781da11dc91d6eb59a40fb3d2a7c28ba7a66  0.0s
>  => => naming to docker.io/library/bookwyrm-celery_worker                                 0.0s
>  => [celery_worker] resolving provenance for metadata file                                0.0s
> [+] Creating 5/4
>  ✔ Network bookwyrm_main                Created                                           0.1s 
>  ✔ Container bookwyrm-redis_activity-1  Created                                           0.2s 
>  ✔ Container bookwyrm-redis_broker-1    Created                                           0.2s 
>  ✔ Container bookwyrm-db-1              Created                                           0.2s 
>  ✔ Container bookwyrm-celery_worker-1   Created                                           0.0s 
> [+] Running 4/4
>  ✔ Container bookwyrm-db-1              Started                                           1.0s 
>  ✔ Container bookwyrm-redis_activity-1  Started                                           1.0s 
>  ✔ Container bookwyrm-redis_broker-1    Started                                           0.9s 
>  ✔ Container bookwyrm-celery_worker-1   Started                                           0.6s 
> [+] Building 0.6s (12/12) FINISHED                                              docker:default
>  => [web internal] load build definition from Dockerfile                                  0.0s
>  => => transferring dockerfile: 303B                                                      0.0s
>  => [web internal] load metadata for docker.io/library/python:3.11                        0.4s
>  => [web internal] load .dockerignore                                                     0.0s
>  => => transferring context: 97B                                                          0.0s
>  => [web 1/6] FROM docker.io/library/python:3.11@sha256:38b425945de90afd3c9159309bda02be  0.0s
>  => [web internal] load build context                                                     0.0s
>  => => transferring context: 38B                                                          0.0s
>  => CACHED [web 2/6] RUN mkdir /app /app/static /app/images                               0.0s
>  => CACHED [web 3/6] WORKDIR /app                                                         0.0s
>  => CACHED [web 4/6] RUN apt-get update && apt-get install -y gettext libgettextpo-dev t  0.0s
>  => CACHED [web 5/6] COPY requirements.txt /app/                                          0.0s
>  => CACHED [web 6/6] RUN pip install -r requirements.txt --no-cache-dir                   0.0s
>  => [web] exporting to image                                                              0.0s
>  => => exporting layers                                                                   0.0s
>  => => writing image sha256:ce71eccb49a8af1c5e4d43de640817ab84e4bad21f3aef2b1cca76dbf311  0.0s
>  => => naming to docker.io/library/bookwyrm-web                                           0.0s
>  => [web] resolving provenance for metadata file                                          0.0s
> Operations to perform:
>   Apply all migrations: admin, auth, bookwyrm, contenttypes, django_celery_beat, oauth2_provider, sessions
> Running migrations:
>   Applying bookwyrm.0004_tag...Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
>     return self.cursor.execute(sql)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
> psycopg2.errors.DuplicateTable: relation "bookwyrm_tag" already exists
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/app/manage.py", line 18, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
>     output = self.handle(*args, **options)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
>     res = handle_func(*args, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
>     post_migrate_state = executor.migrate(
>                          ^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
>     state = self._migrate_all_forwards(
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
>     state = self.apply_migration(
>             ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
>     state = migration.apply(state, schema_editor)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 132, in apply
>     operation.database_forwards(
>   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/models.py", line 96, in database_forwards
>     schema_editor.create_model(model)
>   File "/usr/local/lib/python3.11/site-packages/pgtrigger/migrations.py", line 420, in create_model
>     super().create_model(model)
>   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 451, in create_model
>     self.execute(sql, params or None)
>   File "/usr/local/lib/python3.11/site-packages/pgtrigger/migrations.py", line 404, in execute
>     return super().execute(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/schema.py", line 45, in execute
>     return super().execute(sql, params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 201, in execute
>     cursor.execute(sql, params)
>   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
>     return self._execute_with_wrappers(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
>     return executor(sql, params, many, context)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
>     with self.db.wrap_database_errors:
>   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
>     return self.cursor.execute(sql)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
> django.db.utils.ProgrammingError: relation "bookwyrm_tag" already exists

**Expected behavior**
Success message.

**Additional context**
I've tried several times to install Bookwyrm, and I thought it could be due to having executed the migrate command more than once, but I tried also deleting all docker images and starting from scratch with a fresh clone of the repository. Same error.

---

**Desktop (please complete the following information):**
    - OS: Ubuntu 24.04

**Comment by winterjodi** [comment]
I managed to fix this.
I edited the bw-dev script, and in the case "resetdb", I commented out temporarily the command "prod_error", and executed `./bw-dev resetdb`. After that, I was able to continue without issue.

Must have been some leftover of my previous tests, although I can't figure out why, since I removed all the docker processes and images...
