### ISSUE TITLE
Can’t search for or mention an octodon.social account

### ISSUE THREAD

**Issue by ldidry** [bookwyrm-social/bookwyrm#3415]
**Describe the bug**
I tried to mention an account from octodon.social but I get a server error. Same thing when searching for the same user.

**To Reproduce**
1. Search for `@Bouletcorp@octodon.social`
2. Get a server error

**Expected behavior**
I should be able to see and mention the account.

**Instance**
My own instance, https://bw.fiat-tux.fr. Version 0.7.4

**Additional context**
It seems to be a problem with [`AUTHORIZED_FETCH`](https://docs.joinmastodon.org/admin/config/#authorized_fetch) setting on octodon.social and the signature created by Bookwyrm. See [this ticket](https://github.com/glitch-soc/mastodon/issues/2443).

**Error log**
<details>
<summary>Click to see the log</summary>
<div class="snippet-clipboard-content notranslate position-relative overflow-auto"><pre class="notranslate"><code class="notranslate">OK: /search
Traceback (most recent call last):
  File "/var/www/bookwyrm/bookwyrm/views/helpers.py", line 84, in handle_remote_webfinger
    user = models.User.objects.get(username__iexact=query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
bookwyrm.models.user.User.DoesNotExist: User matching query does not exist.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/www/bookwyrm/bookwyrm/activitypub/base_activity.py", line 372, in resolve_remote_id
    data = get_data(remote_id)
           ^^^^^^^^^^^^^^^^^^^
  File "/var/www/bookwyrm/bookwyrm/connectors/abstract_connector.py", line 337, in get_data
    resp.raise_for_status()
  File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://octodon.social/users/Bouletcorp
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/csp/decorators.py", line 20, in _wrapped
    r = f(*a, **kw)
        ^^^^^^^^^^^
  File "/var/www/bookwyrm/bookwyrm/views/search.py", line 51, in get
    return endpoints[search_type](request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/bookwyrm/bookwyrm/views/search.py", line 133, in user_search
    handle_remote_webfinger(query)
  File "/var/www/bookwyrm/bookwyrm/views/helpers.py", line 100, in handle_remote_webfinger
    user = activitypub.resolve_remote_id(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/bookwyrm/bookwyrm/activitypub/base_activity.py", line 379, in resolve_remote_id
    data = get_activitypub_data(remote_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/bookwyrm/bookwyrm/activitypub/base_activity.py", line 436, in get_activitypub_data
    try:
        ^
  File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://octodon.social/users/Bouletcorp
Forbidden (Permission denied): /inbox
Traceback (most recent call last):
  File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/bookwyrm/bookwyrm/views/inbox.py", line 44, in post
    raise_is_blocked_activity(activity_json)
  File "/var/www/bookwyrm/bookwyrm/views/inbox.py", line 93, in raise_is_blocked_activity
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
</code></pre></div>
</details>

**Comment by hughrun** [comment]
Hi @ldidry 

Thanks for the log. I think your analysis is correct. This is still happening occassionally and I have a potential fix coming for this but it may take a few weeks.

The main reason this could be happening is if you're accidentally running BookWyrm single-threaded - it happens because we're sending two http requests within the same loop. 

A couple of questions:
- Are you running on Docker or dockerless? 
- And are you using the latest `production` branch? 
 
Your command to start up should look something like this:

```sh
gunicorn bookwyrm.wsgi:application --threads=8 --bind 0.0.0.0:8000
```

**Comment by ldidry** [comment]
I’m using BW dockerless, with the latest production branch (tag v0.7.4, I upgraded before reporting the bug).

I didn’t specified the `--threads` option on my start command. Once I added `--threads=2` (very small server), it worked!

Thank you for the tip.
