### ISSUE TITLE
 Bookwyrm service doesn't start due to missing celery module (under Yunohost)

### ISSUE THREAD

**Issue by mapperfr** [bookwyrm-social/bookwyrm#3475]
I'm using Bookwyrm through Yunohost (bookwyrm 0.7.2~ynh2).  I've posted [a bug report](https://github.com/YunoHost-Apps/bookwyrm_ynh/issues/67) on the bookwyrm_ynh bug tracker but as I'm not sure if this issue is Yunohost related or not, I'll report it here too!

**Describe the bug**

Under Yunohost 12.0.6, Bookwyrm service fails. It seems to be due to a missing celery module. I did the upgrade to YH 12 on Nov. 5th and unsuccessfully tried to restart the service on Nov. 13. Here's the log of bookwyrm-beat:

```
  - Nov 05 20:05:54 celery[1234]:     self.ensure_connection()
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
  - Nov 05 20:05:54 celery[1234]:     return func(*args, **kwargs)
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
  - Nov 05 20:05:54 celery[1234]:     self.connect()
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
  - Nov 05 20:05:54 celery[1234]:     raise dj_exc_value.with_traceback(traceback) from exc_value
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
  - Nov 05 20:05:54 celery[1234]:     self.connect()
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
  - Nov 05 20:05:54 celery[1234]:     return func(*args, **kwargs)
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
  - Nov 05 20:05:54 celery[1234]:     self.connection = self.get_new_connection(conn_params)
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
  - Nov 05 20:05:54 celery[1234]:     return func(*args, **kwargs)
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
  - Nov 05 20:05:54 celery[1234]:     connection = Database.connect(**conn_params)
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
  - Nov 05 20:05:54 celery[1234]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  - Nov 05 20:05:54 celery[1234]: django.db.utils.OperationalError: could not connect to server: Connection refused
  - Nov 05 20:05:54 celery[1234]:         Is the server running on host "localhost" (::1) and accepting
  - Nov 05 20:05:54 celery[1234]:         TCP/IP connections on port 5432?
  - Nov 05 20:05:54 celery[1234]: could not connect to server: Connection refused
  - Nov 05 20:05:54 celery[1234]:         Is the server running on host "localhost" (127.0.0.1) and accepting
  - Nov 05 20:05:54 celery[1234]:         TCP/IP connections on port 5432?
  - Nov 05 20:09:39 systemd[1]: Stopping bookwyrm-beat.service - bookwyrm celery beat process...
  - Nov 05 20:09:46 celery[1234]: celery beat v5.2.7 (dawn-chorus) is starting.
  - Nov 05 20:09:46 celery[1234]: __    -    ... __   -        _
  - Nov 05 20:09:46 celery[1234]: LocalTime -> 2024-08-14 09:17:34
  - Nov 05 20:09:46 celery[1234]: Configuration ->
  - Nov 05 20:09:46 celery[1234]:     . broker -> redis://localhost:6379/0
  - Nov 05 20:09:46 celery[1234]:     . loader -> celery.loaders.app.AppLoader
  - Nov 05 20:09:46 celery[1234]:     . scheduler -> django_celery_beat.schedulers.DatabaseScheduler
  - Nov 05 20:09:46 celery[1234]:     . logfile -> [stderr]@%INFO
  - Nov 05 20:09:46 celery[1234]:     . maxinterval -> 5.00 seconds (5s)
  - Nov 05 20:09:47 systemd[1]: bookwyrm-beat.service: Deactivated successfully.
  - Nov 05 20:09:47 systemd[1]: Stopped bookwyrm-beat.service - bookwyrm celery beat process.
  - Nov 05 20:09:47 systemd[1]: bookwyrm-beat.service: Consumed 5h 7min 28.157s CPU time.
  - -- Boot 474ec49f7064465baa590691e851f37d --
  - Nov 05 20:10:01 systemd[1]: Started bookwyrm-beat.service - bookwyrm celery beat process.
  - Nov 05 20:10:02 celery[1327]: Traceback (most recent call last):
  - Nov 05 20:10:02 celery[1327]:   File "/var/www/bookwyrm/venv/bin/celery", line 5, in <module>
  - Nov 05 20:10:02 celery[1327]:     from celery.__main__ import main
  - Nov 05 20:10:02 celery[1327]: ModuleNotFoundError: No module named 'celery'
  - Nov 05 20:10:02 systemd[1]: bookwyrm-beat.service: Main process exited, code=exited, status=1/FAILURE
  - Nov 05 20:10:02 systemd[1]: bookwyrm-beat.service: Failed with result 'exit-code'.
  - Nov 13 10:59:23 systemd[1]: Started bookwyrm-beat.service - bookwyrm celery beat process.
  - Nov 13 10:59:23 (celery)[165426]: bookwyrm-beat.service: Failed to locate executable /var/www/bookwyrm/venv/bin/celery: No such file or directory
  - Nov 13 10:59:23 (celery)[165426]: bookwyrm-beat.service: Failed at step EXEC spawning /var/www/bookwyrm/venv/bin/celery: No such file or directory
  - Nov 13 10:59:23 systemd[1]: bookwyrm-beat.service: Main process exited, code=exited, status=203/EXEC
  - Nov 13 10:59:23 systemd[1]: bookwyrm-beat.service: Failed with result 'exit-code'.
  ``` 

**Instance**
Instance is https://b.falai.se.
The server is a Raspberry Pi 4 / Olimex A20, lime2, running Debian 12 bookworm & YunoHost 12.0.6

**Desktop (please complete the following information):**
    - OS: NixOS
    - Browser: Firefox 
    - Version: 132.0.2

**Comment by mapperfr** [comment]
Closing this issue as it is somehow fixed. No idea what happened though, and I lost all the images I uploaded in the process. See [the bookwyrm_ynh bug report](https://github.com/YunoHost-Apps/bookwyrm_ynh/issues/67).
