### ISSUE TITLE
Tasks processing deleted statuses from Mastodon fail

### ISSUE THREAD

**Issue by tofuwabohu** [bookwyrm-social/bookwyrm#956]
Most or all status deletion notifications I get in flower failed. Somehow, there are many of them, they currently make more than 60% of all existent tasks.

![image](https://user-images.githubusercontent.com/66644064/115127721-09703400-9fd9-11eb-86d7-dc0d7f9902ca.png)

Details: `Exception | ActivitySerializerError('Missing required field: cc')`

```
Traceback (most recent call last):
  File "/app/bookwyrm/activitypub/base_activity.py", line 77, in __init__
    value = kwargs[field.name]
KeyError: 'cc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/bookwyrm/views/inbox.py", line 93, in activity_task
    activity = activitypub.parse(activity_json)
  File "/app/bookwyrm/activitypub/__init__.py", line 31, in parse
    return naive_parse(activity_objects, activity_json)
  File "/app/bookwyrm/activitypub/base_activity.py", line 61, in naive_parse
    return serializer(activity_objects=activity_objects, **activity_json)
  File "/app/bookwyrm/activitypub/base_activity.py", line 98, in __init__
    raise ActivitySerializerError(
bookwyrm.activitypub.base_activity.ActivitySerializerError: Missing required field: cc
```
There are some from mastodon.online as well so I guess it's a problem with Mastodon in general, even though pipou.academy sends out a lot of deletes.

**Comment by mouse-reeve** [comment]
Yeah, this has been bugging me too! It should be fixed by #955
